version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "sport_live"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
    volumes:
    - ./db:/var/lib/mysql
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    image: 'sport-laravel'
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html